openapi: 3.0.1
info:
  contact:
    email: chuck.marco@prattwhitney.com
    name: Chuck Marco
    url: https://chuck-nbc.fandom.com/wiki/Marco
  description: RESTful API for Pratt & Whitney DOME Application.
  title: Digital Overhaul Management of Engines
  version: 2021-09-28
externalDocs:
  description: Project SharePoint
servers:
- description: DBDS Devlelopment
  url: http://192.168.3.171:81/dome
- description: DBDS Stage
  url: http://192.168.3.171:82/dome
- description: P&W Stage
  url: https://dome-ui-test.prattwhitney.com/dome
security:
- bearerAuth: []
tags:
- description: "MRO (maintenance, repair and operations) Collaboration API."
  name: MRO Collab
paths:
  /v1/mro-collab/comments:
    delete:
      description: Sample MRO API to delete the matching Comment record.
      operationId: updateEngineComments_3
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MroCommentDeleteRequest'
        required: true
      responses:
        "204":
          content:
            application/json:
              schema:
                type: object
          description: Successfully deleted the matching record.
        "404":
          content:
            application/json:
              schema:
                type: object
          description: Not Found
      tags:
      - MRO Collab
    post:
      description: Sample MRO API to update the supplied comment record.
      operationId: updateEngineComments_1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MroComment'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MroComment'
          description: Successfully updated the matching comment record.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MroComment'
          description: Not Found
      tags:
      - MRO Collab
  /v1/mro-collab/pacing-items:
    delete:
      description: Sample MRO API to delete the matching PacingItem record.
      operationId: updateEngineComments_2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MroPacingItemDeleteRequest'
        required: true
      responses:
        "204":
          content:
            application/json:
              schema:
                type: object
          description: Successfully deleted the matching record.
        "404":
          content:
            application/json:
              schema:
                type: object
          description: Not Found
      tags:
      - MRO Collab
  /v1/mro-collab/pacing-items/{engine-id}:
    put:
      description: Sample MRO API to update the PacingItem record.
      operationId: updateEngineComments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MroPacingItem'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MroPacingItem'
          description: Successfully updated the matching pacing-item record.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MroPacingItem'
          description: Not Found
      tags:
      - MRO Collab
  /v1/mro-collab/workorder:
    delete:
      description: Deletes the matching EngineTracking MRO work order.
      operationId: deleteWorkOrderFromMRO
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MroWorkOrderDeleteRequest'
        required: true
      responses:
        "204":
          content:
            application/json:
              schema:
                type: object
          description: WorkOrder dropped for matching EngineTracking record.
        "400":
          content:
            application/json:
              examples:
                All request values fail validation.:
                  description: All request values fail validation.
                  summary: All request values made to fail validation.
                  value:
                    status: BAD_REQUEST
                    statusCode: 400
                    reason: Bad Request
                    message: "Validation failed for argument [0] in public org.springframework.http.ResponseEntity<?>\
                      \ com.pw.dome.mro.collab.workorder.MroWorkOrderController.deleteWorkOrderFromMRO(com.pw.dome.mro.collab.workorder.MroWorkOrderDeleteRequest)\
                      \ with 3 errors: [Field error in object 'mroWorkOrderDeleteRequest'\
                      \ on field 'mroShopCode': rejected value [ESAdskndsduhsudhisuhdshdshdhsdsdhishdis];\
                      \ codes [Size.mroWorkOrderDeleteRequest.mroShopCode,Size.mroShopCode,Size.java.lang.String,Size];\
                      \ arguments [org.springframework.context.support.DefaultMessageSourceResolvable:\
                      \ codes [mroWorkOrderDeleteRequest.mroShopCode,mroShopCode];\
                      \ arguments []; default message [mroShopCode],10,1]; default\
                      \ message [size must be between 1 and 10]] [Field error in object\
                      \ 'mroWorkOrderDeleteRequest' on field 'eventId': rejected value\
                      \ [-1]; codes [Min.mroWorkOrderDeleteRequest.eventId,Min.eventId,Min.java.lang.Integer,Min];\
                      \ arguments [org.springframework.context.support.DefaultMessageSourceResolvable:\
                      \ codes [mroWorkOrderDeleteRequest.eventId,eventId]; arguments\
                      \ []; default message [eventId],1]; default message [must be\
                      \ greater than or equal to 1]] [Field error in object 'mroWorkOrderDeleteRequest'\
                      \ on field 'esn': rejected value [723821odaauasashashashahsuhaushuahsasas];\
                      \ codes [Size.mroWorkOrderDeleteRequest.esn,Size.esn,Size.java.lang.String,Size];\
                      \ arguments [org.springframework.context.support.DefaultMessageSourceResolvable:\
                      \ codes [mroWorkOrderDeleteRequest.esn,esn]; arguments []; default\
                      \ message [esn],20,1]; default message [size must be between\
                      \ 1 and 20]]"
                    errors:
                    - "mroShopCode: size must be between 1 and 10"
                    - "eventId: must be greater than or equal to 1"
                    - "esn: size must be between 1 and 20"
                One request value fails validation.:
                  description: One request value fails validation.
                  summary: One request value is null and fails validation.
                  value:
                    status: BAD_REQUEST
                    statusCode: 400
                    reason: Bad Request
                    message: "Validation failed for argument [0] in public org.springframework.http.ResponseEntity<?>\
                      \ com.pw.dome.mro.collab.workorder.MroWorkOrderController.deleteWorkOrderFromMRO(com.pw.dome.mro.collab.workorder.MroWorkOrderDeleteRequest):\
                      \ [Field error in object 'mroWorkOrderDeleteRequest' on field\
                      \ 'eventId': rejected value [null]; codes [NotNull.mroWorkOrderDeleteRequest.eventId,NotNull.eventId,NotNull.java.lang.Integer,NotNull];\
                      \ arguments [org.springframework.context.support.DefaultMessageSourceResolvable:\
                      \ codes [mroWorkOrderDeleteRequest.eventId,eventId]; arguments\
                      \ []; default message [eventId]]; default message [must not\
                      \ be null]]"
                    errors:
                    - "eventId: must not be null"
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "404":
          content:
            application/json:
              examples:
                EventId doesn't match.:
                  description: EventId doesn't match.
                  summary: Error response when request EventId not matched.
                  value:
                    status: NOT_FOUND
                    statusCode: 404
                    reason: Not Found
                    message: 'No matching records to update found. ESN=''723821''
                      has 1 match(es). EventId=''40436799'' has 0 match(es). ShopCode=''ESA''
                      has 3737 match(es). '
                    errors:
                    - 'No matching records to update found. ESN=''723821'' has 1 match(es).
                      EventId=''40436799'' has 0 match(es). ShopCode=''ESA'' has 3737
                      match(es). '
                ShopCode doesn't match.:
                  description: ShopCode doesn't match.
                  summary: Error response when request ShopCode not matched.
                  value:
                    status: NOT_FOUND
                    statusCode: 404
                    reason: Not Found
                    message: 'No matching records to update found. ESN=''723821''
                      has 1 match(es). EventId=''4043679'' has 1 match(es). ShopCode=''ESAAA''
                      has 0 match(es). '
                    errors:
                    - 'No matching records to update found. ESN=''723821'' has 1 match(es).
                      EventId=''4043679'' has 1 match(es). ShopCode=''ESAAA'' has
                      0 match(es). '
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
      tags:
      - MRO Collab
    post:
      description: Updates the matching EngineTracking record with the MRO work order.
      operationId: updateWorkOrderFromMRO
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MroWorkOrderUpdateRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: WorkOrder updated for matching EngineTracking record.
        "400":
          content:
            application/json:
              examples:
                All request values fail validation.:
                  description: All request values fail validation.
                  summary: All request values made to fail validation.
                  value:
                    status: BAD_REQUEST
                    statusCode: 400
                    reason: Bad Request
                    message: "Validation failed for argument [0] in public org.springframework.http.ResponseEntity<java.lang.String>\
                      \ com.pw.dome.mro.collab.workorder.MroWorkOrderController.getMroInfo(com.pw.dome.mro.collab.workorder.MroWorkOrderRequest)\
                      \ with 4 errors: [Field error in object 'mroWorkOrderRequest'\
                      \ on field 'mroShopCode': rejected value [ESAjidjowjdosjdoijsdojsodjsdoisd];\
                      \ codes [Length.mroWorkOrderRequest.mroShopCode,Length.mroShopCode,Length.java.lang.String,Length];\
                      \ arguments [org.springframework.context.support.DefaultMessageSourceResolvable:\
                      \ codes [mroWorkOrderRequest.mroShopCode,mroShopCode]; arguments\
                      \ []; default message [mroShopCode],10,1]; default message [length\
                      \ must be between 1 and 10]] [Field error in object 'mroWorkOrderRequest'\
                      \ on field 'esn': rejected value [72382112902912912091290120912098u12];\
                      \ codes [Length.mroWorkOrderRequest.esn,Length.esn,Length.java.lang.String,Length];\
                      \ arguments [org.springframework.context.support.DefaultMessageSourceResolvable:\
                      \ codes [mroWorkOrderRequest.esn,esn]; arguments []; default\
                      \ message [esn],20,1]; default message [length must be between\
                      \ 1 and 20]] [Field error in object 'mroWorkOrderRequest' on\
                      \ field 'eventId': rejected value [-1]; codes [Range.mroWorkOrderRequest.eventId,Range.eventId,Range.java.lang.Integer,Range];\
                      \ arguments [org.springframework.context.support.DefaultMessageSourceResolvable:\
                      \ codes [mroWorkOrderRequest.eventId,eventId]; arguments [];\
                      \ default message [eventId],9223372036854775807,1]; default\
                      \ message [must be between 1 and 9223372036854775807]] [Field\
                      \ error in object 'mroWorkOrderRequest' on field 'mroWorkOrder':\
                      \ rejected value [0123456789mjdoiasjodjnwoidjowdjoidjoihjndo];\
                      \ codes [Length.mroWorkOrderRequest.mroWorkOrder,Length.mroWorkOrder,Length.java.lang.String,Length];\
                      \ arguments [org.springframework.context.support.DefaultMessageSourceResolvable:\
                      \ codes [mroWorkOrderRequest.mroWorkOrder,mroWorkOrder]; arguments\
                      \ []; default message [mroWorkOrder],25,1]; default message\
                      \ [length must be between 1 and 25]]"
                    errors:
                    - "mroShopCode: length must be between 1 and 10"
                    - "esn: length must be between 1 and 20"
                    - "eventId: must be between 1 and 9223372036854775807"
                    - "mroWorkOrder: length must be between 1 and 25"
                One request value fails validation.:
                  description: One request value fails validation.
                  summary: One request value is null and fails validation.
                  value:
                    status: BAD_REQUEST
                    statusCode: 400
                    reason: Bad Request
                    message: "Validation failed for argument [0] in public org.springframework.http.ResponseEntity<java.lang.String>\
                      \ com.pw.dome.mro.collab.workorder.MroWorkOrderController.getMroInfo(com.pw.dome.mro.collab.workorder.MroWorkOrderRequest):\
                      \ [Field error in object 'mroWorkOrderRequest' on field 'eventId':\
                      \ rejected value [null]; codes [NotNull.mroWorkOrderRequest.eventId,NotNull.eventId,NotNull.java.lang.Integer,NotNull];\
                      \ arguments [org.springframework.context.support.DefaultMessageSourceResolvable:\
                      \ codes [mroWorkOrderRequest.eventId,eventId]; arguments [];\
                      \ default message [eventId]]; default message [The field may\
                      \ not be null.]]"
                    errors:
                    - "eventId: The field may not be null."
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "404":
          content:
            application/json:
              examples:
                ESN doesn't match.:
                  description: ESN doesn't match.
                  summary: Error response when request ESN not matched.
                  value:
                    status: NOT_FOUND
                    statusCode: 404
                    reason: Not Found
                    message: 'No matching records to update found. ESN=''72382111''
                      has 0 match(es). EventId=''4043679'' has 1 match(es). ShopCode=''ESA''
                      has 3737 match(es). '
                    errors:
                    - 'No matching records to update found. ESN=''72382111'' has 0
                      match(es). EventId=''4043679'' has 1 match(es). ShopCode=''ESA''
                      has 3737 match(es). '
                ShopCode doesn't match.:
                  description: ShopCode doesn't match.
                  summary: Error response when request ShopCode not matched.
                  value:
                    status: NOT_FOUND
                    statusCode: 404
                    reason: Not Found
                    message: 'No matching records to update found. ESN=''723821''
                      has 1 match(es). EventId=''4043679'' has 1 match(es). ShopCode=''ESAAA''
                      has 0 match(es). '
                    errors:
                    - 'No matching records to update found. ESN=''723821'' has 1 match(es).
                      EventId=''4043679'' has 1 match(es). ShopCode=''ESAAA'' has
                      0 match(es). '
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
      tags:
      - MRO Collab
components:
  schemas:
    ErrorResponse:
      type: object
      description: Error response schema.
      properties:
        errors:
          type: array
          description: Chain of application error messages.
          items:
            type: string
            description: Chain of application error messages.
        message:
          type: string
          description: Application error message.
        reason:
          type: string
          description: "The HttpStatus Reason Phrase  (e.g., NOT FOUND)."
        status:
          type: string
          description: "The HttpStatus name (e.g., NOT_FOUND)."
        statusCode:
          type: integer
          format: int32
          description: "The HttpStatus value  (e.g., 404)."
    MroComment:
      type: object
      description: Comment DTO schema.
      properties:
        commentId:
          type: integer
          format: int32
        dateUpdated:
          type: string
          format: date-time
        engineId:
          type: integer
          format: int32
        esn:
          type: string
          maxLength: 20
          minLength: 1
        eventId:
          type: integer
          format: int32
          minimum: 1
        external:
          type: boolean
        logEmail:
          type: string
          maxLength: 50
          minLength: 1
        mroShopCode:
          type: string
          maxLength: 10
          minLength: 1
        mroWorkOrder:
          type: string
          description: Named SMI in MRO system.
          maxLength: 25
          minLength: 1
        notes:
          type: string
          maxLength: 2000
          minLength: 1
      required:
      - commentId
      - dateUpdated
      - engineId
      - esn
      - eventId
      - external
      - logEmail
      - mroShopCode
      - mroWorkOrder
      - notes
    MroCommentDeleteRequest:
      type: object
      description: Comment delete request schema.
      properties:
        commentId:
          type: integer
          format: int32
        engineId:
          type: integer
          format: int32
        esn:
          type: string
          maxLength: 20
          minLength: 1
        eventId:
          type: integer
          format: int32
          minimum: 1
        mroShopCode:
          type: string
          maxLength: 10
          minLength: 1
        mroWorkOrder:
          type: string
          description: Named SMI in MRO system.
          maxLength: 25
          minLength: 1
      required:
      - commentId
      - engineId
      - esn
      - eventId
      - mroShopCode
      - mroWorkOrder
    MroPacingItem:
      type: object
      description: PacingItem DTO schema.
      properties:
        category:
          type: string
          maxLength: 20
          minLength: 0
        closeDate:
          type: string
          format: date
        commitDate:
          type: string
          format: date
        datReceivedDate:
          type: string
          format: date
        datShipOutDate:
          type: string
          format: date
        description:
          type: string
          maxLength: 50
          minLength: 0
        dollarsSaved:
          type: integer
          format: int32
        engineId:
          type: integer
          format: int32
        engineSN:
          type: string
          maxLength: 10
          minLength: 1
        escItem:
          type: boolean
        esn:
          type: string
          maxLength: 20
          minLength: 1
        eventId:
          type: integer
          format: int32
          minimum: 1
        holdDaysApproved:
          type: integer
          format: int32
        logDateTime:
          type: string
          format: date-time
        mroShopCode:
          type: string
          maxLength: 10
          minLength: 1
        mroWorkOrder:
          type: string
          description: Named SMI in MRO system.
          maxLength: 25
          minLength: 1
        needDate:
          type: string
          format: date
        notes:
          type: string
          maxLength: 2000
          minLength: 0
        pacingId:
          type: integer
          format: int32
        partId:
          type: string
          maxLength: 20
          minLength: 0
        purchaseOrder:
          type: string
          maxLength: 10
          minLength: 0
        startDate:
          type: string
          format: date
        subCategory:
          type: string
          maxLength: 20
          minLength: 0
        uniqueId:
          type: string
          maxLength: 20
          minLength: 0
        vendorInDate:
          type: string
          format: date
        vendorName:
          type: string
          maxLength: 30
          minLength: 0
        vendorOutDate:
          type: string
          format: date
        wsInd:
          type: string
          maxLength: 20
          minLength: 0
      required:
      - category
      - closeDate
      - commitDate
      - datReceivedDate
      - datShipOutDate
      - description
      - engineId
      - engineSN
      - escItem
      - esn
      - eventId
      - mroShopCode
      - mroWorkOrder
      - pacingId
    MroPacingItemDeleteRequest:
      type: object
      description: PacingItem delete request schema.
      properties:
        category:
          type: string
          maxLength: 20
          minLength: 0
        closeDate:
          type: string
          format: date
        commitDate:
          type: string
          format: date
        datReceivedDate:
          type: string
          format: date
        datShipOutDate:
          type: string
          format: date
        description:
          type: string
          maxLength: 50
          minLength: 0
        dollarsSaved:
          type: integer
          format: int32
        engineId:
          type: integer
          format: int32
        engineSN:
          type: string
          maxLength: 10
          minLength: 1
        escItem:
          type: boolean
        esn:
          type: string
          maxLength: 20
          minLength: 1
        eventId:
          type: integer
          format: int32
          minimum: 1
        holdDaysApproved:
          type: integer
          format: int32
        logDateTime:
          type: string
          format: date-time
        mroShopCode:
          type: string
          maxLength: 10
          minLength: 1
        mroWorkOrder:
          type: string
          description: Named SMI in MRO system.
          maxLength: 25
          minLength: 1
        needDate:
          type: string
          format: date
        notes:
          type: string
          maxLength: 2000
          minLength: 0
        pacingId:
          type: integer
          format: int32
        partId:
          type: string
          maxLength: 20
          minLength: 0
        purchaseOrder:
          type: string
          maxLength: 10
          minLength: 0
        startDate:
          type: string
          format: date
        subCategory:
          type: string
          maxLength: 20
          minLength: 0
        uniqueId:
          type: string
          maxLength: 20
          minLength: 0
        vendorInDate:
          type: string
          format: date
        vendorName:
          type: string
          maxLength: 30
          minLength: 0
        vendorOutDate:
          type: string
          format: date
        wsInd:
          type: string
          maxLength: 20
          minLength: 0
      required:
      - category
      - closeDate
      - commitDate
      - datReceivedDate
      - datShipOutDate
      - description
      - engineId
      - engineSN
      - escItem
      - esn
      - eventId
      - mroShopCode
      - mroWorkOrder
      - pacingId
    MroWorkOrderDeleteRequest:
      type: object
      description: Delete work order schema.
      properties:
        esn:
          type: string
          maxLength: 20
          minLength: 1
        eventId:
          type: integer
          format: int32
          minimum: 1
        mroShopCode:
          type: string
          maxLength: 10
          minLength: 1
      required:
      - esn
      - eventId
      - mroShopCode
    MroWorkOrderUpdateRequest:
      type: object
      description: Update work order schema.
      properties:
        esn:
          type: string
          maxLength: 20
          minLength: 1
        eventId:
          type: integer
          format: int32
          minimum: 1
        mroShopCode:
          type: string
          maxLength: 10
          minLength: 1
        mroWorkOrder:
          type: string
          description: Named SMI in MRO system.
          maxLength: 25
          minLength: 1
      required:
      - esn
      - eventId
      - mroShopCode
      - mroWorkOrder
  securitySchemes:
    bearerAuth:
      bearerFormat: jwt
      description: JWT Bearer Authorization.
      scheme: bearer
      type: http
